### ISSUE TITLE
bof? state incorrect when streaming multibyte characters

### ISSUE THREAD

**Issue by ojundt** [jasoncodes/filter_io#10]
Hey, great work! Everything seems to work so far except for a small bug I came across when filtering a UTF-8 StringIO with BOM and checking for beginning of file `bof?`.

```
input_stream = StringIO.new("\xEF\xBB\xBFtest123")
FilterIO.new(input_stream) { |chunk, state| puts state.bof?; chunk }
# prints false. Expected true
```

I was able to pinpoint it to: https://github.com/jasoncodes/filter_io/blob/39275f5ccfdcac5f038f77c6af83d092923daf9c/lib/filter_io.rb#L370
`data.length` is counting characters but should count bytes. Shouldn't it be `data.bytesize`?

**Comment by jasoncodes** [comment]
Thanks for the great bug report! I agree that `data.length` should be `data.bytesize` and have pushed out v0.2.8 with this fix. Cheers.
